// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP3._11.DAL;

#nullable disable

namespace TP3._11.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240908052957_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TP3._11.Models.Passaporte", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Passaportes");
                });

            modelBuilder.Entity("TP3._11.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("TP3._11.Models.Passaporte", b =>
                {
                    b.HasOne("TP3._11.Models.Pessoa", "Pessoa")
                        .WithOne("Passaporte")
                        .HasForeignKey("TP3._11.Models.Passaporte", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("TP3._11.Models.Pessoa", b =>
                {
                    b.Navigation("Passaporte");
                });
#pragma warning restore 612, 618
        }
    }
}
